// <auto-generated />
namespace GestProv.InfraestructuraDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class entidadesnuevas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entidadesnuevas));
        
        string IMigrationMetadata.Id
        {
            get { return "202212031327559_entidades nuevas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
